---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: observability
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 58.5.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: base
  interval: 30m
  releaseName: prometheus
  targetNamespace: observability
  values: {}

